# Generated by Django 5.1.1 on 2024-10-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=50)),
                ('sort_description', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=50)),
                ('date_of_birth', models.CharField(max_length=50)),
                ('website_link', models.URLField(max_length=1000)),
                ('phone', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('age', models.PositiveBigIntegerField()),
                ('Degree', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
