# Generated by Django 5.1.1 on 2024-10-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
