# Generated by Django 5.1.1 on 2024-10-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_about_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('link_icon', models.CharField(max_length=100)),
            ],
        ),
    ]
